<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\Fonts\**" />
    <Compile Remove="Model\**" />
    <EmbeddedResource Remove="Assets\Fonts\**" />
    <EmbeddedResource Remove="Model\**" />
    <None Remove="Assets\Fonts\**" />
    <None Remove="Model\**" />
    <Page Remove="Assets\Fonts\**" />
    <Page Remove="Model\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\icoCoffee.ico" />
    <None Remove="Assets\Images\cuteCoffeeCup.jpg" />
    <None Remove="Assets\Images\imgBanner_1.png" />
    <None Remove="Assets\Images\imgBanner_2.png" />
    <None Remove="Assets\Images\imgBanner_3.png" />
    <None Remove="Assets\Images\imgBanner_4.png" />
    <None Remove="Assets\Images\imgBanner_5.jpg" />
    <None Remove="Assets\Images\imgCoffeeOrder.jpg" />
    <None Remove="Assets\Images\imgItemExample.jpg" />
    <None Remove="Assets\Images\imgMessageBox.png" />
    <None Remove="Assets\Images\Menu\imgBongLanTrungMuoi.png" />
    <None Remove="Assets\Images\Menu\imgCaPheDaXay.png" />
    <None Remove="Assets\Images\Menu\imgCFBacXiu.png" />
    <None Remove="Assets\Images\Menu\imgCFCotDua.png" />
    <None Remove="Assets\Images\Menu\imgCFDen.png" />
    <None Remove="Assets\Images\Menu\imgCFDenDa.png" />
    <None Remove="Assets\Images\Menu\imgCFMuoi.png" />
    <None Remove="Assets\Images\Menu\imgCFSuaDa.png" />
    <None Remove="Assets\Images\Menu\imgCFTrung.png" />
    <None Remove="Assets\Images\Menu\imgChocolateDaXay.png" />
    <None Remove="Assets\Images\Menu\imgColdBrewCamSa.png" />
    <None Remove="Assets\Images\Menu\imgCookiesDaXay.png" />
    <None Remove="Assets\Images\Menu\imgCrossant.png" />
    <None Remove="Assets\Images\Menu\imgEpCam.png" />
    <None Remove="Assets\Images\Menu\imgEpDuaHau.png" />
    <None Remove="Assets\Images\Menu\imgEpDuaLuoi.png" />
    <None Remove="Assets\Images\Menu\imgEpThom.png" />
    <None Remove="Assets\Images\Menu\imgMatchaDaXay.png" />
    <None Remove="Assets\Images\Menu\imgMochaDaXay.png" />
    <None Remove="Assets\Images\Menu\imgPannaCotta.png" />
    <None Remove="Assets\Images\Menu\imgSinhToBo.png" />
    <None Remove="Assets\Images\Menu\imgSinhToDau.png" />
    <None Remove="Assets\Images\Menu\imgSinhToMangCau.png" />
    <None Remove="Assets\Images\Menu\imgSinhToSauRieng.png" />
    <None Remove="Assets\Images\Menu\imgTraChanh.png" />
    <None Remove="Assets\Images\Menu\imgTraDao.png" />
    <None Remove="Assets\Images\Menu\imgTrangCuon.png" />
    <None Remove="Assets\Images\Menu\imgTrangTron.png" />
    <None Remove="Assets\Images\Menu\imgTraSenNhan.png" />
    <None Remove="Assets\Images\Menu\imgTraThanhLong.png" />
    <None Remove="Assets\Images\Menu\imgTraTraiCay.png" />
    <None Remove="Assets\Images\Menu\imgTraVaiHoaHong.png" />
    <None Remove="Assets\Images\Menu\imgTSGaoRang.png" />
    <None Remove="Assets\Images\Menu\imgTSKemCheese.png" />
    <None Remove="Assets\Images\Menu\imgTSMatcha.png" />
    <None Remove="Assets\Images\Menu\imgTSTiramisu.png" />
    <None Remove="Assets\Images\Menu\imgTSTruyenThong.png" />
    <None Remove="Assets\Images\MessageBoxIcons\imgError.png" />
    <None Remove="Assets\Images\MessageBoxIcons\imgInfo.png" />
    <None Remove="Assets\Images\MessageBoxIcons\imgQuestion.png" />
    <None Remove="Assets\Images\MessageBoxIcons\imgSuccess.png" />
    <None Remove="Assets\Images\MessageBoxIcons\imgWarning.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icoCoffee.ico" />
    <Resource Include="Assets\Images\imgBanner_4.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EPPlus" Version="8.3.1" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1-ci1190" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\cuteCoffeeCup.jpg" />
    <Resource Include="Assets\Images\imgBanner_1.png" />
    <Resource Include="Assets\Images\imgBanner_2.png" />
    <Resource Include="Assets\Images\imgBanner_3.png" />
    <Resource Include="Assets\Images\imgBanner_5.jpg" />
    <Resource Include="Assets\Images\imgCoffeeOrder.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\imgItemExample.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\imgMessageBox.png" />
    <Resource Include="Assets\Images\Menu\imgBongLanTrungMuoi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCaPheDaXay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFBacXiu.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFCotDua.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFDen.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFDenDa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFMuoi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFSuaDa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCFTrung.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgChocolateDaXay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgColdBrewCamSa.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCookiesDaXay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgCrossant.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgEpCam.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgEpDuaHau.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgEpDuaLuoi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgEpThom.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgMatchaDaXay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgMochaDaXay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgPannaCotta.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgSinhToBo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgSinhToDau.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgSinhToMangCau.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgSinhToSauRieng.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraChanh.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraDao.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTrangCuon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTrangTron.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraSenNhan.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraThanhLong.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraTraiCay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTraVaiHoaHong.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTSGaoRang.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTSKemCheese.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTSMatcha.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTSTiramisu.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Menu\imgTSTruyenThong.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\MessageBoxIcons\imgError.png" />
    <Resource Include="Assets\Images\MessageBoxIcons\imgInfo.png" />
    <Resource Include="Assets\Images\MessageBoxIcons\imgQuestion.png" />
    <Resource Include="Assets\Images\MessageBoxIcons\imgSuccess.png" />
    <Resource Include="Assets\Images\MessageBoxIcons\imgWarning.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Images\Items\" />
  </ItemGroup>

</Project>
